import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LocaleHtml from "@/components/LocaleHtml";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Locale-aware html attributes updater for /en route */}
        {/* This ensures <html> lang/dir match the current locale at runtime */}
        {/* Client-side updater to keep <html> lang/dir in sync with locale */}
        <LocaleHtml />
        <Header />
        <main className="mx-auto max-w-5xl [padding-inline:1rem] md:[padding-inline:2rem] py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
