import type { Metadata } from "next";
import { Cairo, Amiri, Merriweather } from "next/font/google";
import "./globals.css";
import LocaleHtml from "@/components/LocaleHtml";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const uiSans = Cairo({
  variable: "--font-ui",
  weight: ["400", "500", "700"],
  subsets: ["arabic", "latin"],
});

const serifAr = Amiri({
  variable: "--font-serif-ar",
  weight: ["400", "700"],
  subsets: ["arabic", "latin"],
});

const serifEn = Merriweather({
  variable: "--font-serif-en",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" suppressHydrationWarning>
      <body className={`${uiSans.variable} ${serifAr.variable} ${serifEn.variable} antialiased`}>
        {/* Locale-aware html attributes updater for /en route */}
        {/* This ensures <html> lang/dir match the current locale at runtime */}
        {/* Client-side updater to keep <html> lang/dir in sync with locale */}
        <LocaleHtml />
        <Header />
        <main className="mx-auto max-w-4xl px-4 sm:px-6 md:px-8 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
